title: ShenLab Conference Deadlines
description: Countdowns to relevant AD/AI/Bioinfo/Imaging/Medical-info conference deadlines. You can select the filters of conference types; and can also navigate conference dates in the calendar page and export to your own calendar
# description: Countdowns to relevant AD/AI/Bioinfo/Imaging/Medical-info conference deadlines related to ShenLab. You can select the filters of conference types; and can also navigate conference dates in the calendar page and export to your own calendar
author: Shu Yang

domain: "https://PennShenLab.github.io/"
baseurl: "/submission-deadlines"

# twitter:
#   username: AlexN4u
#   hashtag: machinelearning
github_username: PennShenLab
github_repo: submission-deadlines

markdown: kramdown
ga_id: UA-166050497-2

include: ["_pages"]
